### ISSUE TITLE
Poke-Controllerの実行ができない

### ISSUE THREAD

**Issue by superd241** [KawaSwitch/Poke-Controller#13]
はじめまして。
5のPoke-Controllerの実行が何度やってもできないのですが教えていただけると幸いです。
必要なパッケージはすべてインストール済みなのはanaconda navigatorで確認してあります。

**Comment by KawaSwitch** [comment]
いくつか状況の確認をさせて頂きます

- 使用OS
- Poke-Controllerのバージョン
どのページのどれをDLしたかでも構いません
- 実行時の状況
ウィンドウは出る/ウィンドウも出ないなど
実行時のAnaconda PromptとPoke-Controllerのスクリーンショットもあると助かります
- 何かしらのエラーメッセージは出ているか

以上4点について, ご回答お願いいたします

**Comment by superd241** [comment]
初心者で分からないことだらけですいません。
使用OSはwindous10です。
Poke-Controllerのバージョンは1.0beta
Window.pyのファイルを実行するとこの表示が出て先に進むことが出来ません
![2](https://user-images.githubusercontent.com/60834044/74098883-a7a87480-4b60-11ea-9d90-00f394063ba3.jpg)

![無題](https://user-images.githubusercontent.com/60834044/74098818-b4789880-4b5f-11ea-9965-a9ca11aecf31.jpg)

**Comment by KawaSwitch** [comment]
Pythonファイルの実行時は先頭に`python`が必要です
`python C:¥Users¥...¥Window.py`
としてみてください

**Comment by superd241** [comment]
無事実行してウィンドウが開きました。
お手数かけてすいません。ありがとうございました。

**Comment by KawaSwitch** [comment]
いえいえ、無事実行できたようで良かったです！
ご質問ありがとうございました
