### ISSUE TITLE
Can I detect vibration motor signals?

### ISSUE THREAD

**Issue by arithxp** [KawaSwitch/Poke-Controller#25]
Is there any way to detect the vibration motor signal?

**Comment by KawaSwitch** [comment]
No, there isn't way to catch the vibration signals.
You can't do that because [Switch-Fightstick](https://github.com/progmem/Switch-Fightstick) (the project I forked from) provides descriptors for the Pokken controller that doesn't have HD rumble feature.

**Comment by arithxp** [comment]
Thank you for your quick reply.
Too bad HD rumble is not supported.
