### ISSUE TITLE
通信が上手くいかない

### ISSUE THREAD

**Issue by nlxqa** [KawaSwitch/Poke-Controller#26]
32u4なのでjoystick.hexをコンパイルし、書き込みました。
Switchに接続したところ、初回のLとRボタンの入力が勝手に行われただけで、入力がソフトから送信されませんでした。ソフト側での表示ではCOMポートへの接続はうまく行っているようです。
他のコントローラーソフトでは上手く通信できていたのでハード側は問題ないと思います。
書き込むJoystick.hexに問題があるのでしょうか？
よろしくお願いします。

**Comment by KawaSwitch** [comment]
長らく気づかずに申し訳ありませんでした。
提示されている情報からすると元となるJoystick.cが古いか, Joystick.hexの書き込み時に何かしら問題がある可能性がありますが, 手元に32u4が無いため動作確認することが出来ず他にも色々原因が考えられると思います。

期間が空いていますので一旦閉じますが、何かあれば再度Reopenをお願いします。
