### ISSUE TITLE
半自動色違い厳選

### ISSUE THREAD

**Issue by pokeaka** [KawaSwitch/Poke-Controller#32]
初めてながら書いてみました

固定シンボルを起動時に即リポップさせる方法
ttps://twitter.com/KOU50060275/status/1304618465739730944
これを使用してpoke controllerから再起動、遭遇（目視または音で確認）、再起動を繰り返すことで野生色違いを集めることができます

[](https://xfs.jp/E7rCuT) 
pw repop

**Comment by pokeaka** [comment]
リンクがないですね…すみません
ttps://xfs.jp/E7rCuT

**Comment by KawaSwitch** [comment]
返事が遅くなり申し訳ありません。とても実装が早くて驚いています！

ファイル分け実装にしてからは初めて共有して頂いたのでどこにコマンドを置こうか迷っていたのですが, Wikiの方にデフォルト以外のコマンドとして参照リンクとともに載せさせて頂きます。
