### ISSUE TITLE
キャプチャーボードについて

### ISSUE THREAD

**Issue by iamgarugaru** [KawaSwitch/Poke-Controller#35]
無知で申し訳ないのですが、UVC対応キャプチャーボードがどういうものか分からないので教えてもらってよろしいですか？
AVerMedia Live Gamer HD 2 C988　っていうPC内蔵型のキャプチャーボードを使っているのですが画像認識に使えますか？

**Comment by KawaSwitch** [comment]
UVCに対応していればドライバのインストール等不要で初心者でも簡単に導入できるため記述しています。
お使いの AVerMedia Live Gamer HD 2 C988 でも画像認識は行えます。

ただ、その際は以下のIssueにあるように取り込み解像度を720pへ変更してもらう必要があるかもしれません。
既知のバグですがまだ修正が完了していません。
[Issue: LGP Stream Engineを用いた画像認識が行えない](https://github.com/KawaSwitch/Poke-Controller/issues/5)

**Comment by iamgarugaru** [comment]
ありがとうございました！
