### ISSUE TITLE
Poke-Controllerの導入について

### ISSUE THREAD

**Issue by iamgarugaru** [KawaSwitch/Poke-Controller#37]
度々すみません。
4.マイコンをUSBデバイス化するがどうしてもうまくいきません
PowerShellでdfu-programmerを起動しようとしても反応が無いのですが、どうしたらいいですか？
マイコンはELEGOO Arduino Uno R3 です
![image](https://user-images.githubusercontent.com/73905919/98389288-2d793200-2097-11eb-9bc8-29d75a07e509.png)
![image](https://user-images.githubusercontent.com/73905919/98389418-5b5e7680-2097-11eb-88d2-cf32967b45a6.png)

**Comment by KawaSwitch** [comment]
見たことない状況ですね...。
とりあえず下記コマンドを実行したとき, PowerShell上でどのように表示されるかを教えてください。

```
.\dfu-programmer.exe --version
```
```
.\dfu-programmer.exe --targets
```

また, erase後のflash, reset時も同じように何も表示されないでしょうか？

**Comment by KawaSwitch** [comment]
念のためPCの再起動後に実行をお願いします。

**Comment by iamgarugaru** [comment]
PCの再起動後、全てのコマンド入力してみましたが反応がありません。
自分でももう少し調べてみます
![image](https://user-images.githubusercontent.com/73905919/98445641-089ac280-215c-11eb-8589-537d9b442f3f.png)

**Comment by KawaSwitch** [comment]
```
echo "a"
```
ものは試しなのですが, これの実行結果はどうなりますかね？

**Comment by iamgarugaru** [comment]
とりあえず、進展として伝えときます
dfu-programmer単体で起動しようとすると以下の感じになるので
![image](https://user-images.githubusercontent.com/73905919/98446537-75fd2200-2161-11eb-9567-404b24b92acd.png)
dfu-programmer-win-0.7.2\dfu-prog-usb-1.2.2\x86に配置されている
libusb0_x86.dllをlibus0.dllとリネームしてdfu-programmerと同じフォルダ内に配置しました

そして、PowerShellでコマンド入力後、反応はあったのですがマイコンが認識されてないという感じでした。
![image](https://user-images.githubusercontent.com/73905919/98446628-1d7a5480-2162-11eb-8b8f-15ca4ae0efae.png)

デバイスマネージャーを開いて確認もしてみましたが
![image](https://user-images.githubusercontent.com/73905919/98446692-9679ac00-2162-11eb-9a35-da1744d02be5.png)
atmega16u2としては認識されていないような感じです。
接続手順も間違ってはいないとは思うのですが。。。。
マイコンを買いなおした方がよさそうですか？

**Comment by KawaSwitch** [comment]
DFUモードに入ったArduinoを接続した際, デバイスマネージャ上では"不明なデバイス"もしくは"Atmel USB Devices"として表示されるはずです。
USBシリアルデバイスと表示されているのはシリアル変換器などではないでしょうか？
といいつつ, 私もハード側には詳しくないので的外れかもしれませんが...

**Comment by KawaSwitch** [comment]
また, [この記事](https://another.maple4ever.net/archives/2380/)のようにドライバを指定してデバイスを認識させるところまでの流れが必要かもしれません。
そもそもショートからDFUモードに入れればの話ですがどうでしょうか？

**Comment by iamgarugaru** [comment]
そうですね。
試してみたのですがダメでした。
ショートの解除前後でPCの反応も無いですね...
マイコンを触ったことがないのでどの状態でDFUモードに入ってるのか分からないのでなんとも判断できないです。
個人的には初期不良であってほしいと願っているのですが（笑）
Amazonで購入しましたし、返送もそこまで大変ではないので一度買いなおしてみて
ダメだったらもう一度考えます！

**Comment by KawaSwitch** [comment]
私も最初は純正品を使っていましたが, 現在は同じAmazonで購入した"ELEGOO Arduino Uno R3"で動いているので謎ですね...

デバイスマネージャ上ではショート外して"不明なデバイス"もしくは"Atmel USB Devices"として表示されればDFUモードに入っています。
ハードの不良であればまだ良い（良くはないけど）のですがあまりお力になれず申し訳ないです。
