### ISSUE TITLE
画像認識の範囲指定

### ISSUE THREAD

**Issue by inukaizohyo** [KawaSwitch/Poke-Controller#39]
はじめまして。
Poke-Controllerの画像認識について質問があります。

画像認識の際、認識させる範囲を画面上の指定範囲内に収める（例えば画面の上半分にあるテンプレート画像は認識させて下半分にある同じ画像は認識させない）といったことは可能でしょうか？
もし可能であるとしたら、どのようなプログラムを組めば良いでしょうか？
なにぶんプログラムについては素人同然であるため無知な質問ではあるかも知れませんが、よろしくお願いします。

**Comment by KawaSwitch** [comment]
先ほどのコミット 9c70a2a2e69e223b56c0eff65d8006afa14afa3e で対応しました（現在テンプレートマッチングのみ）。
引数として領域を指定し、次のように使用できます。

area: キャプチャ画像をトリミングする領域.  
tmp_area: テンプレート画像をトリミングする領域.  
いずれもリスト形式 [x_begin, x_end, y_begin, y_end] で指定.  

```
self.isContainTemplate('hoge.png', area=[0, 320, 100, 200])
キャプチャ画像の X:0~319, Y:100~199 の領域にテンプレート画像が存在するか判定

self.isContainTemplate('hoge.png', area=[0, 320, 100, 200], tmp_area=[0, 30, 0, 30])
キャプチャ画像の X:0~319, Y:100~199 の領域にテンプレート画像の X:0~29, Y:0~29 の部分が存在するか判定
```

**Comment by ShunPoteMobe** [comment]
お世話になっております。
上記対応が施されたisContainTemplateメソッドの使い方について質問です。

追加された引数area、tmp_areaを指定していない状態で本メソッドをコールした場合、下記ステップにて配列参照外のエラーが出てしまいました。
`		src = src[area[2]:area[3], area[0]:area[1]] if not area else src # trim`
		
`		template = template[tmp_area[2]:tmp_area[3], tmp_area[0]:tmp_area[1]] # trim`
		
■エラー内容
  File "***\Poke-Controller-master\SerialController\Commands\PythonCommandBase.py", line 174, in isContainTemplate
    src = src[area[2]:area[3], area[0]:area[1]] if not area else src # trim
IndexError: list index out of range

本対応後、範囲指定を行わずにメソッドをコールする（キャプチャ画像もテンプレート画像もトリミングしないで使用したい）場合はどのようにコールすればよろしいでしょうか。
現在はひとまず上記処理だけコメントアウトしてしまっています。

お忙しいところお手数ですがご教示頂ければと思います。

**Comment by Moi-poke** [comment]
2021/08/22, 1:17　編集
こちらの問題について，ちょっと考えてみました．(時間経っているので参考になるかわかりませんが)

コード見直したところ，
` src = src[area[2]:area[3], area[0]:area[1]] if not area else src # trim`
空リストはFalseを返すので想定の逆の挙動をしていると思います．(area = []のときtrueになる)
areaのエラーで止まってるので不明ですが，tmp_areaも未指定だと同様のエラーが出る気がします．同様の処理で対応可能かなと思います．

2021/10/29, 19:55 追記, 2021/11/28 編集
見返してみるとどう変更すればよいか書いていませんでした．解決済みのコメントに記載されていますが，
誤
` src = src[area[2]:area[3], area[0]:area[1]] if not area else src # trim`
`template = template[tmp_area[2]:tmp_area[3], tmp_area[0]:tmp_area[1]] # trim`
正
` src = src[area[2]:area[3], area[0]:area[1]] if area else src # trim`
`template = template[tmp_area[2]:tmp_area[3], tmp_area[0]:tmp_area[1]] if tmp_area else template # trim`
となります．

**Comment by ShunPoteMobe** [comment]
お忙しいところ回答頂き有難うございます。

つまり
`src = src[area[2]:area[3], area[0]:area[1]] if area else src # trim`
とすればよいということですかね。
上記の対応をPythonCommandBase.pyの該当処理部と、同様の形式でtmp_areaを用いる処理に対しても反映したところ、area・tmp_areaを引数指定しなくても問題なく動作することが確認できました。

有難うございました。
