### ISSUE TITLE
pokecontrollerが開きません

### ISSUE THREAD

**Issue by riruvaly** [KawaSwitch/Poke-Controller#40]
導入方法を見ながらやっているのですがWindowsを開くとエラーになります……。プログラムのことは一切分からないので勉強しろと言われればそれまでなのですが、解決方法が分かれば教えていただけると有難いです。よろしくお願いします
![20201215_115733](https://user-images.githubusercontent.com/76037111/102189737-6e683000-3efa-11eb-84bf-cd7efdfa21b4.jpg)

**Comment by aquanpoke** [comment]
通りすがりのものです。
私もこちらのエラーが出たことがあるので共有です。

私の場合、こちらのエラーは回避できず、別バージョンのPokeControllerを利用しました。

そちらのエラーは、以下サイトでの”安定版”を利用されていませんか？
https://github.com/KawaSwitch/Poke-Controller/wiki/Poke-Controller%E3%81%AE%E4%BD%BF%E3%81%84%E6%96%B9

”安定版”ではなく、”最新版”をインストールし、アナコンダで実行することで私は起動することができました。
直接的な回答ではありませんが、ご参考までに。
