### ISSUE TITLE
PokeControllerのSerialControllerに移動できない

### ISSUE THREAD

**Issue by chimoon12** [KawaSwitch/Poke-Controller#42]
分からないので質問させていただきます。
他の方の導入記事(安定版）を参考にここまできたのですが、windowpyを開く為にPokeControllerのSerialController内にアクセスしようとするのですが指定されたパスが見つかりませんと出ます。PokeControllerはデスクトップに置いてありプロンプトでも確認済みです。もう一歩のところでつまってしまったので解決策を教えていただけると幸いです。

**Comment by izyuumi** [comment]
[このガイド](https://pokecontroller.info/)を参考に試してみてください。自分はこれに沿ってやったらうまくいきました。
