### ISSUE TITLE
新しいPythonコマンドが認識されない

### ISSUE THREAD

**Issue by hirolton** [KawaSwitch/Poke-Controller#49]
初歩的なことかと思いますが、質問させていただきます。

新しいPythonコマンドの作り方（以下URL）の通りに、pyファイルを作成いたしましたが、Poke-Controllter上でReloadや再起動をしてもプルダウンに表示されません。
https://github.com/KawaSwitch/Poke-Controller/wiki/%E6%96%B0%E3%81%97%E3%81%84Python%E3%82%B3%E3%83%9E%E3%83%B3%E3%83%89%E3%81%AE%E4%BD%9C%E3%82%8A%E6%96%B9

ファイルはほぼコピペで以下のように作成いたしました。
「test.py」
#!/usr/bin/env python3
# -*- coding: utf-8 -*-

from Commands.PythonCommandBase import PythonCommand, ImageProcPythonCommand
from Commands.Keys import KeyPress, Button, Hat, Direction, Stick

class Something(PythonCommand):
	NAME = '何か'

	def __init__(self):
		super().__init__()

	def do(self):
		pass

使用環境は以下の通りです。
Poke-Controllter ver 1.0-beta3
Windows 10 Home

デフォルトで入っている機能は認識され、switch上でもきちんと動作しております。
ちなみに、他の方が提供してくださっているpyファイルを指定通りのディレクトリに保存しても認識されないので、ファイル内容に問題はないのかと思っております。

対処法にお心当たりございましたらお願いいたします。
よろしくお願いいたします。

**Comment by kuchikarabotamochi** [comment]
同様の事象で困っています。
どのような手法で解決しましたか？
