### ISSUE TITLE
LGP Stream Engineを用いた画像認識が行えない

### ISSUE THREAD

**Issue by xv13** [KawaSwitch/Poke-Controller#5]
### ■動作環境
PC : Windows 10 Home(64bit)
キャプボ : AVerMedia AVT-C875

Python : 3.8.1
cv2 : opencv-contrib-python(v4.1.2.30)

### ■問題点
「Poke-Controller」を使用した際に、画像認識が真っ暗で動作しない。
(その際、別のソフトなどでキャプボの画面出力は行っていません。)

### ■確認内容

1. Poke-ControllerでのLGP Stream Engineの動作確認
![Poke-Controller-master](https://user-images.githubusercontent.com/47322147/72221455-48296a00-359e-11ea-817c-cfd504f22ff8.PNG)
CameraID:0(AverMedia C875 Capture) -> 「CameraID0can'topen.」
CameraID:1(LGP Stream Engine) -> 真っ黒な画面が表示される。
CameraID:2-9(割り当て無し) -> 「CameraID0can'topen.」

2. フリーソフトでのLGP Stream Engineの動作確認
![AGC](https://user-images.githubusercontent.com/47322147/72221462-5bd4d080-359e-11ea-94c4-15a5f8041907.PNG)
こちら( http://t-ishii.la.coocan.jp/download/AGCRec.html )のフリーソフトにて、
LGP Stream EngineがPC上で正常に動作することの確認を行いました。

キャプボやPythonのバージョンなどに問題があるのでしょうか？
もし解決方法をご存じであれば、ご教授いただければ幸いです。

操作方法や動作要件を満たしていなかったらすみません。

**Comment by Moi-poke** [comment]
開発者ではないので見当違いな推測かもしれませんが、LGP Stream Engineの設定で取り込み解像度を720p (1280×720)にすると映るようになるかもしれません。(自分はGV-USB3/HDとアマレコ+ライブ機能の拡張を使用して取り込んでいますが、1080pだと同じ黒画面になり、720pにすると映りました。)

**Comment by xv13** [comment]
Moi-poke様
ご回答いただきありがとうございます。

Moi-poke様の仰る通りに取り込み解像度を720pにすることで映像を取り込めるようになりました。
誠にありがとうございます。

**Pokemon Controller動作画面**
![Pokemon Controller](https://user-images.githubusercontent.com/47322147/72229429-daa72900-35f1-11ea-9b62-b792c1a25f77.PNG)

**AVerMedia Stream Engine設定画面**
![AVerMedia Stream Engine](https://user-images.githubusercontent.com/47322147/72229441-f01c5300-35f1-11ea-9059-734558883e5d.PNG)

**Comment by KawaSwitch** [comment]
情報提供ありがとうございます
1080pの取り込み解像度で黒画面となる不具合について把握いたしました
ただこの状況を私の環境で再現できないため現在この問題自体の修正は困難です

不便をおかけして申し訳ありませんが同様の不具合が出てしまう方は, Moi-poke様の方法でのキャプチャをお願いいたします
何かしら分かったことがあったら追記いたします
