### ISSUE TITLE
PythonコマンドのHATボタンについて

### ISSUE THREAD

**Issue by Raysta02** [KawaSwitch/Poke-Controller#50]
お世話になっております。
Pythonコマンド_作成How_toにてHATボタンの使用例が無いのですが教えていただけないでしょうか？
self.press(Hat.RIGHT, 1.0, 0.5) と書いたのですがエラーになってしまい動きませんでした。

**Comment by KawaSwitch** [comment]
```
from Commands.Keys import KeyPress, Button, Direction, Stick, Hat
```

使用法は合っています。このようにHatクラスをimportしているか確認してみてください。
解決しない場合は、エラー文をすべて貼り付けてください。

**Comment by Raysta02** [comment]
おっしゃる通りHatクラスのimportが抜けておりました。完全に盲点でした。
ありがとうございました。
