### ISSUE TITLE
GUIの起動について

### ISSUE THREAD

**Issue by agnnn-ag** [KawaSwitch/Poke-Controller#7]
こんにちは。GUIをどこから開けるのか分からず、困っています。教えてもらえますか？

**Comment by KawaSwitch** [comment]
ご利用いただきありがとうございます。
すみません。まだどこにも書いていませんでした。

[簡易 使用方法]
PokeController/SerialController/Window.py
の実行でGUIが起動します。
python3の環境を整えて必要なパッケージをいくつか導入してから実行する必要があります。

**Comment by agnnn-ag** [comment]
ご回答ありがとうございます。コマンドプロンプトが一瞬起動してすぐに消えてしまうのですが、どうしたらいいですか？
tkinter PIL はインストールしました。

**Comment by KawaSwitch** [comment]
Windowsにpython環境を構築する際はAnacondaなど導入されていますか
もしくはtkinter, PILはサイトからダウンロードしたインストーラなどを用いてインストールされたということでしょうか
また何かエラーメッセージ等はありますか？

**Comment by KawaSwitch** [comment]
tkinter, PIL以外に用いている主なパッケージは次の通りです
- pyserial
- pynput
- pythonnet
- OpenCV

**Comment by KawaSwitch** [comment]
丁度新しいPCがあったので以下Windows10+Anacondaで再度試してみました
あくまで一例ですがご参考になれば幸いです

1. Anacondaインストール
[ここ](https://www.anaconda.com/distribution/#download-section)から3.7の方を選択してDL→インストール

2. 下記画像のように"Anaconda Prompt"があるので開く
![win10_anaconda_prompt](https://user-images.githubusercontent.com/41296626/72659081-7c1ce900-39fd-11ea-8ec7-91e5a45836ea.PNG)

3. 次のコマンドをすべて実行し環境を整える
`conda create -n [name] python=3.6`
バージョン3.6でしか動かないパッケージがあるので指定
[name]の部分は好きな仮想環境名に変更
`conda activate [name]`
`pip install opencv-python` (OpenCV)
`pip install pynput` (pynput)
`conda install pyserial` (pyserial)
`conda install Pillow` (PIL)
`conda install -c pythonnet pythonnet` (pythonnet)

4. Poke-Controller/SerialControllerまで移動
`cd [Poke-Controllerまでのパス]\Poke-Controller\SerialController`

5. 実行
`python Window.py`

**Comment by agnnn-ag** [comment]
ご丁寧な説明をいただき感謝です。教えていただいて通り行ったところ、起動するのを確認しました。応答なしの状態が続いているのですが、ほかに必要事項はありますでしょうか。

**Comment by KawaSwitch** [comment]
私の環境ではこれで起動できましたので必要事項はそろっているはずです
応答なし、というのはどういった状態でしょうか
お手数をかけますが該当箇所のスクリーンショットなどを撮って貼って頂けるとありがたいです

**Comment by agnnn-ag** [comment]
![poke-controller](https://user-images.githubusercontent.com/59998966/72660679-2d2e7e00-3a14-11ea-9fd2-52ae029347e7.PNG)
この状態がずっと続いています。よろしくお願いします。

**Comment by agnnn-ag** [comment]
タスクマネージャで応答なしの表示が出ています。

**Comment by KawaSwitch** [comment]
スクショありがとうございます
v1.0-alphaバージョンをダウンロードしてもらっているみたいですね
一旦git pullして最新にするか, [Poke-Controller ホーム](https://github.com/KawaSwitch/Poke-Controller)の"Clone or Download"ボタン→"Download ZIP"から最新バージョンを落として実行してみて頂けますか

**Comment by agnnn-ag** [comment]
![anaconda prompt](https://user-images.githubusercontent.com/59998966/72662008-b77ede00-3a24-11ea-824e-489bf76ffac3.PNG)
zipを解凍し、anaconda prompt から開いてみたところ、このような表示となりました。重ね重ねの質問となりますが、お教えください。

**Comment by KawaSwitch** [comment]
Poke-Controller-masterのフォルダ内にDirectShowLibというフォルダはありますか？

**Comment by agnnn-ag** [comment]
あります。
DirectShowLib-2005.dll
lisence.txt
readme.txt
WhatsNew.txt
が入っています。

**Comment by KawaSwitch** [comment]
Poke-Controller-master/SerialController/Window.pyの192行目の"/"をバックスラッシュに変えて保存し実行できるか試してみてほしいです
Windows環境ではバックスラッシュは￥マークと表示されるかもしれませんが同じ意味です

clr.AddReference("..\DirectShowLib\DirectShowLib-2005")

**Comment by agnnn-ag** [comment]
先ほどの画像と全く同じ表示になりました...

**Comment by KawaSwitch** [comment]
.dllにセキュリティがかかっているかもしれません
.dllを右クリック→全般タブに[ここ](https://www.atmarkit.co.jp/ait/articles/1603/11/news050.html)にあるような「ブロック解除」のチェックボックスはありますか？

**Comment by agnnn-ag** [comment]
試してみましたが、特に変化は見られませんでした。

**Comment by KawaSwitch** [comment]
この.dllは64bitOS用だったかもしれません
お使いのOS(Windows10)は32bit/64bitどちらですか？

**Comment by agnnn-ag** [comment]
64bitのほうです。

**Comment by agnnn-ag** [comment]
今、九日前にダウンロードした（2807KBのもの)を展開して重複するものを上書きしたところ、解決してUIが表示されたのですが、これはどういうことなのでしょうね...

**Comment by KawaSwitch** [comment]
このdllは接続されているカメラの名前を取得するために使っているのですが, これ（とそれに関連するコード）を追加したのが5日前なのでそれ以前のものは動くのかもしれません
UIのカメラの部分はIDの直接入力/カメラ名選択のどちらになっていますか？

**Comment by agnnn-ag** [comment]
なるほど、です。直接入力になっていました。

**Comment by agnnn-ag** [comment]
お手を煩わせてしまい、すいませんでした。ご丁寧なアドバイスとても助かりました。開発頑張ってください。

**Comment by KawaSwitch** [comment]
問題の原因の特定にいたらずにすみません
後のバージョンではdll読み込みに失敗したらその機能を使わない（カメラIDを直接入力する）ように変更しようと思います
情報のご提供ありがとうございました
